####################################################################
#ECM Version 1.2 for Minecraft 1.8!                                #
#If you find any bugs please tell me on the plugin page            #
#Here: https://www.spigotmc.org/resources/easychatmanager.27210/   #
####################################################################

#Use '&' for color codes. Like '&a' for green!

# Here you can change the way the chat looks!
# Use %s for the username/message.
# The first %s will be the username, and the second %s will be the message.
ChatFormat: '%prefix% <%displayname%> %suffix% %message%'

#Make a format for a certain group!
GroupFormats:
  default: '%prefix% <%displayname%> %suffix% &7&l%message%'
  Admin: '%prefix% <%displayname%> %suffix% &c&l%message%'

#Set any messages you want the plugin to send!
# MAKE SURE TO ONLY CHANGE THE MESSAGES, NOT THE OPTIONS!
Messages:
  Prefix: '&8[&6&lEasyChatManager&8] &r'
  GlobalChatClear: '&8Chat has been cleared by &6%CLEARER%&8!'
  PlayerChatClear: '&8Your chat was cleared by &6%CLEARER%&8!'
  MuteChat: '&8Chat was muted by &6%MUTER%&8!'
  UnmuteChat: '&8Chat was unmuted  by &6%MUTER%&8!'
  ChatIsMuted: '&8Shh quiet, the chat is sleeping.'
  NoPermission: '&cSorry but you do not have permission for this!'
  